### PR TITLE
fix: export missing polyfills

### PR DESCRIPTION
**Pull request by achingbrain**
I need to use `RTCSessionDescription` but it's not exported so this PR Exports all implemented polyfills.

It exports them as both named exports and properties of the default export for backwards compatibility.

### CODE REVIEW

**Comment by murat-dogan** [comment]
I get an error
```
ReferenceError: RTCCertificate is not defined
```

And shouldn't we also update index.d.ts

**Comment by murat-dogan** [comment]
Thank you for committing.
There is a type check command with typescript in package.json already, but converting the js part to typescript could be also a good point.

Seems good to me,
Thanks.

**Comment by achingbrain** [comment]
Thanks for merging this - do you think it'll get released soon?

**Comment by murat-dogan** [comment]
I can release a new version on Weekend. Is that ok?

**Comment by achingbrain** [comment]
Of course! Thanks 😁

**Comment by murat-dogan** [comment]
0.5.3 released!

**Pull request merged**
