### PR TITLE
add media-send example

### PR DESCRIPTION
**Pull request by Canees**
Signed-off-by: caner

### CODE REVIEW

**Comment by murat-dogan** [comment]
Hi,

Thank you PR, but I can't  get the point?
What is these submodules?

**Comment by Canees** [comment]
It's an example of sending a video from the Raspberry PI to the browser

**Comment by murat-dogan** [comment]
peer-send and peer-recv folders seems like a sub repo. 
I can't see the files.

**Comment by Canees** [comment]
> peer-send and peer-recv folders seems like a sub repo. I can't see the files.

Sorry git failed to commit, you are trying

**Pull request closed without merging**
