### PR TITLE
Fix missing GXX env variable in build

### PR DESCRIPTION
**Pull request by leblowl**
In https://github.com/murat-dogan/node-datachannel/pull/282, I forgot to add the GXX environment variable to the actual compilation step

### CODE REVIEW

**Comment by murat-dogan** [comment]
Thanks

**Comment by funniray** [comment]
@murat-dogan and @leblowl I also completely forgot to mention that you have to define the allowed environment variables in the sudo command here
https://github.com/murat-dogan/node-datachannel/blob/master/.github/workflows/build-linux.yml#L94

**Comment by murat-dogan** [comment]
No problem. I didn't see it also.
Addıng now.

**Comment by murat-dogan** [comment]
Compiled successfully. Thanks @funniray

**Pull request merged**
