### PR TITLE
Fix & Cleanup Type Declarations

### PR DESCRIPTION
**Pull request by SE2Dev**
I've included fixes for a few incorrect & unsafe type declarations as well as cleaned up the type declarations in general.

### CODE REVIEW

**Comment by murat-dogan** [comment]
Hi,

Thank you for creating this PR.
There was another PR which I merged. And unfortunately now there are some conflicts.
Sorry for that.

And some notes;
- Please use ' for strings. Maybe I can integrate eslint+prettier to check format.
- Please don't change the format

**Comment by SE2Dev** [comment]
I can resolve the conflicts and remove the quote changes.

I do, however, want to point out that the current type definitions use a style that exists somewhere between the `interface`/`var` class definitions of `lib.dom.d.ts` and the `declare class` declarations that are generated when transpiling classes. While they're functionally equivalent, I'd argue that the second option more clearly indicates intention and is easier to read. I can either revert those changes too, or move them to a separate pull request.

**Comment by murat-dogan** [comment]
Hi @SE2Dev ,

Thank you for noting that.
I have integrated eslint and added a new script `npm run lint`.
I didn't fixed the `lib/index.d.ts` problems.
I will wait for this PR.

**Comment by murat-dogan** [comment]
As I see we need `declare class` arguments and we need to convert `Number` to `number`.

**Comment by SE2Dev** [comment]
I've stripped out all unrelated changes for now.

I'd consider the `declare class` stuff to be more relevant to the other method format changes I had.

It looks like one of the pull requests your merged recently already fixed the type for `PeerConnection.onTrack` so I've removed the changes I had made for that as well.

So at this point the pull request contains changes to better align with common TypeScript [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types), and a change that allows the parameter for `PeerConnection.setLocalDescription()` to be optional (since the wrapper itself will always fallback to Unspec).

**Comment by murat-dogan** [comment]
Looks good.
Thank you.

**Pull request merged**
