### PR TITLE
Dockerfile to build

### PR DESCRIPTION
**Pull request by regnaio**
Files added/modified:
* `Dockerfile`
* `BUILDING.md`

To make sure that the Docker build is valid, I ran a simple test using `node_datachannel.node` from `prebuilds/` with 2 peers sending and receiving messages

### CODE REVIEW

**Comment by murat-dogan** [comment]
Thank you for the PR.
I have tested and seems OK to me.

But It will be built for only node v18. If the user has another version installed then it will be a problem.
Is it possible to take the version number as a parameter or something like that?

And it will be nice if we also install `libnice`. So it will ready as an alternative.
```
# libnice library as an alternative to default one
RUN apt-get install -y libnice-dev
```

**Comment by paullouisageneau** [comment]
I'm sorry, I'm missing the point of this. It looks like the container is used only to build the binary, then you want to use it outside of it. How is it supposed to work in practice?

As @murat-dogan  said, you need to run the same version of node.js on your system, otherwise it'll break. If you add a dependency, like libnice as suggested, it'll break if the same version of libnice is not present on your system. For OpenSSL, it looks like it works by chance because the libssl-dev packages brings the static libraries on Ubuntu, and the build of node-datachannel explicitly requires static libraries on x64. But if you try the same on arm64, it will link dynamically against the library in the container, and you then run the binary on your system at your risks and perils if the version of OpenSSL is not the same. 

It seems to me that you typically run the binary in container too to ensure the whole runtime environment is present and reproducible, rather than mounting the directory only for the build.

**Comment by murat-dogan** [comment]
@paullouisageneau you are right about `libnice`. I forgot `libnice` is dynamically binded. 
Maybe we can keep the file for reference, so the user can adapt it for use case.

**Comment by murat-dogan** [comment]
Since we don't have a solution for all types of builds currently, (Because of the dynamic linking, arm64, etc.) for me keeping that Dockerfile as a reference could be better.

So what about moving this file to examples/build/ folder and writing to Readme something like check examples/build folder for an example Dockerfile for building. In the folder, we can also have an extra file describing the env variables and the procedure. 

If we keep the file in the main folder, users will think it is the formal way of building.

**Comment by murat-dogan** [comment]
Thank you for changes!

**Pull request merged**
