### PR TITLE
Use C++ compiler for CMAKE_CXX_COMPILER env variable

### PR DESCRIPTION
**Pull request by leblowl**
Fixes https://github.com/murat-dogan/node-datachannel/issues/279 for me on amd64 with gcc/g++

### CODE REVIEW

**Comment by murat-dogan** [comment]
Looks ok to me.
Could you also please confirm?
@funniray
@SilentBot1

**Comment by funniray** [comment]
It looks fine to me, but I'm generally unsure what differences invoking g++/clang++ vs just gcc are.

**Comment by leblowl** [comment]
@funniray for me, everything compiled fine, but I think it didn't link the c++ standard lib

**Comment by murat-dogan** [comment]
@leblowl it seems you are right. When I build the lib locally, there is no error for electron.
I have merged the PR, but have some errors on build.
Could you please check it?

https://github.com/murat-dogan/node-datachannel/actions/runs/10864270307/job/30149535154

A note from CMake, from error
```
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is GNU 9.4.0
```

From a successful build
```
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
```

**Comment by funniray** [comment]
re-reviewed the commit and GXX isn't set in the environment variables here.
https://github.com/leblowl/node-datachannel/blob/a4f744ceac3decdc3a3d5b7135dde60bb245a3c6/.github/workflows/build-linux.yml#L100

**Comment by leblowl** [comment]
@funniray good catch! @murat-dogan I opened another PR with the fix: https://github.com/murat-dogan/node-datachannel/pull/291

**Comment by murat-dogan** [comment]
Unfortunately, this did not make any change—the same error.
I tried without Clang++ but it also did not work.
I reverted my changes.

**Comment by murat-dogan** [comment]
@funniray 
We have talked here about binary sizes, remember?
https://github.com/murat-dogan/node-datachannel/pull/264#issuecomment-2185272483

Now with C++ compiler binary sizes are bigger again.

Compare here;
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.11.0
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.12.0-dev

Probably c++ standard file was creating the diff.

**Comment by funniray** [comment]
Yeah, for x64 linux, the v0.12.0 build is much closer in size to the x64 linux v0.9.2 builds, so much of that size could've been from the C++ standard library somehow

**Pull request merged**
