### PR TITLE
FIX types and add CI check for types

### PR DESCRIPTION
**Pull request by pubkey**
The typescript types are broken and throw the following error:

error-types

This PR contains the following:
- Fixes for the typings.
- Update typescript to `5.3.2`.
- Add a CI check to ensure the types will not break in the future.

### CODE REVIEW

**Comment by murat-dogan** [comment]
Could you please add "buıld" to excludes in tsconfıg.json?

**Comment by pubkey** [comment]
@murat-dogan  Yes I have added it in the latest commit.

**Comment by murat-dogan** [comment]
Thanks

**Comment by pubkey** [comment]
@murat-dogan  If you find the time, it would be great to have a new release. This is the last thing that blocks me from using node-datachannel.

**Comment by murat-dogan** [comment]
Just released 0.5.2

**Pull request merged**
